
---
- hosts: all
  gather_facts: yes
  tasks:
    - name: Criar Usuário Ansible
      user:
        name: ansible
        groups: wheel
 
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        backrefs: yes
        dest: /etc/sudoers
        state: present
        regexp: '^# ?%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
